### ISSUE TITLE
Alternative way of finding selected entry

### ISSUE THREAD

**Issue by tosti007** [fdw/rofi-rbw#35]
Currently all entries are serialized into a single string and passed to `rofi` for selection.
In [Rofi's dmenu specs](https://github.com/davatorium/rofi/wiki/dmenu_specs) it is mentioned that it's possible to add a `-format i` argument, which results into the row number being printed instead of the full line. 

This could be used to find the user's selected entry by parsing that number as an int and using it as an index in the entry list. This removes the entire need to splitting the selected entry line to remove the formatting. 

I do want to note that I don't know if this is supported by the other selectors.

What do you think?

**Comment by fdw** [comment]
While this would remove the need for the parsing, it also adds some complexity: Either we require that the ordering of the list stays identical during separate calls (and adding another call to `rbw`, too), or we have to save the whole list somewhere.

Additionally, I don't think a user would expect the rofi menu to be numbered.

**Comment by tosti007** [comment]
The ordering can be fairly easily ensured, since the list of `parsed_entries` can be sorted and used to find the correct index. Currently, between separate calls this list is fully refreshed rather than maintained so by not re-ordering the list this should be solved. 
According to the specs and some quick testing rofi does not print a number in front of each line, rather it only alters the output to stdout.

**Comment by fdw** [comment]
I'm still not sold, sorry. It would avoid the parsing, but add complexity in some other places (either maintaining the list of entries or a second call to `rbw`). Currently, I'm comfortable with the new parsing. So, as long as we don't get a new problem there, I'd keep it as it is.

**Comment by tosti007** [comment]
That's fine!
