### ISSUE TITLE
Wofi shows formatting tags in entry list

### ISSUE THREAD

**Issue by mindrunner** [fdw/rofi-rbw#64]
I guess, that's now how it's supposed to be, right?  Using rofi looks normal.

![image](https://user-images.githubusercontent.com/1413542/205876243-8574d5b9-5211-485d-839d-83eac268390f.png)

**Comment by fdw** [comment]
Yes, that looks like a bug. I'll have a look...

**Comment by mindrunner** [comment]
:)

**Comment by fdw** [comment]
I think this should fix it, but could you please try out the branch `fix/formatting-in-selectors`? Thank you 🙂

**Comment by mindrunner** [comment]
Will check after weekend! Cheers for fixing :)

**Comment by mindrunner** [comment]
How do you start this locally? I always struggle to get things started which use relative imports.

`ImportError: attempted relative import with no known parent package`

**Comment by mindrunner** [comment]
Back to topic: 

looks better now. I still see all entries prefixed with `/`. Same on rofi, tho. I suppose that's intended?

**Comment by fdw** [comment]
> Edit: If I change all imports to absolute, which is the recommended way, I am fine. Maybe you are interested in a Pr for that?

I didn't know that absolute imports are preferred. Can you link me these guidelines, please?
Currently, `rofi-rbw` is on the path to use Poetry, and with that, relative imports work quite fine.

> looks better now.

🥳

>  I still see all entries prefixed with /. Same on rofi, tho. I suppose that's intended?

Yep, that is intended. But I'm open to a discussion 😉

**Comment by mindrunner** [comment]
> Yep, that is intended. But I'm open to a discussion

I like it more without. What's your intention about that?


> Can you link me these guidelines, please?

Quote from [PEP8](http://www.python.org/dev/peps/pep-0008/):

Relative imports for intra-package imports are highly discouraged. Always use the absolute package path for all imports. Even now that [PEP 328](http://www.python.org/dev/peps/pep-0328/) is fully implemented in Python 2.5, its style of explicit relative imports is actively discouraged; absolute imports are more portable and usually more readable.

PR: https://github.com/fdw/rofi-rbw/pull/65

**Comment by fdw** [comment]
You made me curious and I dug a bit, because I couldn't find the paragraph you quoted in [PEP8](https://peps.python.org/pep-0008/) anymore. It seems to have been removed in 2013 with [this commit](https://github.com/python/peps/commit/7dba60ceea8842f00641893295d22338d99cc958), because the new relative syntax avoided some problems the older one had.
There's also [a message by Guido van Rossum](https://mail.python.org/pipermail/python-dev/2010-October/104476.html) about removing the anti-recommendation.

So I think using the new syntax for relative imports seems safe, at least from that perspective. Do you agree? Are there any other reasons to prefer absolute imports?

> What's your intention about that?

Oh, sorry, I made a mistake 🙈 Looking at the code again, it's actually not on purpose, but an artifact when not using folders. I do use folders heavily for everything, so I never noticed you would get a single starting `/` if you don't. Sorry for that wrong comment!
When I have time, I'll adapt this to only show the slash when there is a folder.

**Comment by mindrunner** [comment]
> So I think using the new syntax for relative imports seems safe, at least from that perspective. Do you agree? Are there any other reasons to prefer absolute imports?

You might be right. The quote I presented might have been outdated. I am not too experienced with python and maintain only a proprietary application where I don't use relative imports mainly because `pycharm` semms to really hate them or I am too stupid to set it up correctly. With your code I ran exactly into the same issue I have had already in the past with oder applications/libs.

**Comment by fdw** [comment]
Can you please test the new branch `fix/dont-prefix-slash` if that still works? Thanks :)

Regarding the relative imports, I'd like to wait until `custom-shortcuts` is merged, which brings Poetry. If you still have problems then, we can discuss them (but maybe in a new ticket 😉)

**Comment by fdw** [comment]
Hi @mindrunner, did you have a change yet to test the branch?

**Comment by mindrunner** [comment]
sorry for delay! Looks better now! :)

**Comment by mindrunner** [comment]
Just realized, that you show folder names as prefix of items. (where this issue originates from I suppose). Maybe we could implement a toggle for that? I personally prefer just seeing the items. In a very long list I actually do not care about the folders, so imho does not make sense. Personal preference I suppose and just eyecandy. So nothing important...

**Comment by fdw** [comment]
You can try the branch `feature/no-folder`, there should now be a switch `--no-folder` for you 🙂

**Comment by fdw** [comment]
Hey, if you have a moment, can you please try out the branch and report back? If it works, I'd like to merge it and build a new release.

Thank you 🙂

**Comment by CupricReki** [comment]
I tested the branch, it fixes the no folders issue but now it's returning the entry's name and username instead of username and password.

**Comment by fdw** [comment]
Thanks, there was a bug. I think I fixed it, but can you test again, please? 🙂

**Comment by mindrunner** [comment]
I am trying to test, but getting an 
`
failed to connect socket: No such file or directory
`
error after selecting an entry.

Happens when I start `rofi-rbw` from my Poetry environment. Does not happen on the system wide installation.

**Comment by CupricReki** [comment]
> Thanks, there was a bug. I think I fixed it, but can you test again, please? slightly_smiling_face

Looks good. Prints username and password as expect.

**Comment by fdw** [comment]
> Looks good. Prints username and password as expect.

Thank you 👍

> I am trying to test, but getting an `failed to connect socket: No such file or directory` error after selecting an entry.

But you get the list of all entries?
In any case, that feels more like a problem with your local setup than with the branch, so I'll merge and build a release and then, if the error persists, we can open a new bug. Does that sound okay to you, @mindrunner?
